### PR TITLE
DOC: add `np.fromfunction` example

### PR DESCRIPTION
**Pull request by AntoniosBarotsis**
Added an example that uses `np.vectorize`.

Note that I currently don't have time to check if it renders correctly, although it should be just fine.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
I don't think this "workaround" should be documented as it'll be much slower than broadcasting. Despite it's name, `np.vectorize` does not actually make use of **numpy** vectorization - the implementation uses Python loops

For example:

```python
In [1]: shape = (100, 100)

In [2]: def f(x, y):  # Manual defn of hypot
   ...:     return np.sqrt(x ** 2 + y ** 2)
   ...: 

In [3]: a = np.fromfunction(np.vectorize(f), shape=shape, dtype=float)

In [4]: idx = np.arange(shape[0])

In [5]: b = f(idx[:, np.newaxis], idx[np.newaxis, :])

In [6]: np.array_equal(a, b)
Out[6]: True

In [7]: %timeit a = np.fromfunction(np.vectorize(f), shape=shape, dtype=float)
5.61 ms ± 22.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [8]: %timeit b = f(idx[:, np.newaxis], idx[np.newaxis, :])
20.9 µs ± 41.1 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
I've created the index array explicitly in the above example, but `np.meshgrid` with `sparse=True` can be used to generalize the pattern to higher dimensions.

Personally, I never use vectorize or fromfunction as there is IME always better way to achieve the array you want with a combination of broadcasting and/or advanced indexing, which is far more performant (and readable, IMO).

**Comment by AntoniosBarotsis** [comment]
I feel like this could still be fine for many people as usually creating, in my experience, creating the matrices themselves is not something that happens in a hot path or is the main bottleneck and thus a few milliseconds longer does not matter as much. That said my experience is very limited so you likely know better.

I could replace the example with the code you sent or remove it all together, any thoughts?

**Comment by rossbar** [comment]
> creating the matrices themselves is not something that happens in a hot path or is the main bottleneck and thus a few milliseconds longer does not matter as much.

A 250x slowdown is pretty substantial, even if it's only for something that only happens in initialization. Bump the shape from 100 to 10,000 and your talking about the difference between ~60s and <200 ms.

But for the purposes of documentation, I the performance argument is beside the point. I'm against documenting the workaroud because it doesn't make use of NumPy's powerful features that are better suited for such tasks. Broadcasting is very powerful for dense array creation and advanced indexing is often a far better approach for populating arrays conditionally (i.e. only specific coordinates).

**Comment by AntoniosBarotsis** [comment]
After taking a look at this I agree, changed it in #2

**Pull request merged**
